### ISSUE TITLE
Unable to click links after bypassing HTML sanitation inside gridster

### ISSUE THREAD

**Issue by FrozenGenis** [tiberiuzuld/angular-gridster2#100]
I'm bypassing HTML sanitation through the following pipe method:
https://medium.com/@AAlakkad/angular-2-display-html-without-sanitizing-filtering-17499024b079

This is my HTML:

`<gridster-item [item]="item" *ngFor="let item of dashboard">`
    `<div class="button-holder">`
      `<div class="gridster-item-content">`
        `<div [innerHTML]="item.content | keepHtml"></div>`
      `</div>`
    `</div>`
  `</gridster-item>`

For testing, `item.content` can be a single `<a>` link, such as `<a href="http://google.com">Link</a>`.

After successfully bypassing the sanitation with the pipe `| keepHtml`, click events cannot get to the `<a>` element. Instead, these DOM elements flicker (http://prntscr.com/g5vo5q). Right click -> Open in new tab works as expected though. Removing the pipe `| keepHtml` restores `<a>` click functionality.

The `<a>` works fine outside gridster. I think the `mousedown` event `globalZoneAwareCallback` on `gridster-item`  somehow blocks the click event?

**Comment by tiberiuzuld** [comment]
Hi @FrozenGenis ,
Is from `Enable Click to add` option.
If you disable that option will work.
Working on a fix now.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @FrozenGenis ,

Fixed in v3.11.1

Thanks,

**Comment by FrozenGenis** [comment]
Hello @tiberiuzuld,

Thanks for the quick fix! I've updated but I still encounter the same issue.

Do I still have to disable the `Enable click to add` option? If so, where do I find this option? I tried to look into GridsterConfig but I can't seem to find the option.

Cheers

**Comment by tiberiuzuld** [comment]
Hi @FrozenGenis ,
There is a link in the demo [here](https://tiberiuzuld.github.io/angular-gridster2/angular/)

The option is `enableEmptyCellClick`

On the demo page from the settings at the buttom if is true it works.

**Comment by tiberiuzuld** [comment]
Hi @FrozenGenis ,
On the latest demo page I cannot reproduce the issue anymore.

**Comment by FrozenGenis** [comment]
Hello @tiberiuzuld,

On the demo page, there's no `keepHtml` pipe. Can you try:

**example.component.ts**
`export class Component implements OnInit {`

`...`
`private link: string;`
`...`

`ngOnInit(): void {`
`...`
`this.link= "<a href='http://google.com' target='_blank'>Link</a>";`
`...`

`this.dashboard = [`
`        {cols: 2, rows: 2, y: 0, x: 0, content: this.link},`
`...`
`]`
`}`
`}`

**example.component.html**
`<gridster-item [item]="item" *ngFor="let item of dashboard">`
`<div class="gridster-item-content">`
`        <div [innerHTML]="item.content | keepHtml"></div>`
 `     </div>`
`</gridster-item>`

**keep-html.pipe.ts**
see https://medium.com/@AAlakkad/angular-2-display-html-without-sanitizing-filtering-17499024b079

The important difference is `<div [innerHTML]="item.content | keepHtml"></div>` in **example.component.html**.

**Comment by tiberiuzuld** [comment]
Hi @FrozenGenis ,
Will have a look today.
Thanks

**Comment by FrozenGenis** [comment]
Hello @tiberiuzuld,

I forked your git and tried to reproduce the issue, but no luck. I can't seem to understand why the links work fine in demo but not in my setup.

I created a repository with my code. If you'd like, please have a look and play around with it.

Cheers.

**Comment by tiberiuzuld** [comment]
Hi @FrozenGenis ,

Just tried it and works for me also.

Check the `node_modules` to make sure you have the correct version installed.
Sometimes `npm` doesn't want to install the correct version.

Thanks

**Comment by FrozenGenis** [comment]
Hey @tiberiuzuld ,

Sorry for the inactivity. I was out of it for a week.

I just wanted to confirm: which repository did you try? Was it https://github.com/FrozenGenis/angular-dashboard-PoC? I forgot to mention the link in my previous post. This is the repository with the issue. The fork (https://github.com/FrozenGenis/angular-gridster2) is the repository where I couldn't replicate the issue in the demo.

Cheers

**Comment by tiberiuzuld** [comment]
Hi @FrozenGenis ,
I tested on the demo.
If the issue cannot be reproduce on the demo, is nothing I can do.

Thanks
