### ISSUE TITLE
mobileBreakpoint not applied initially

### ISSUE THREAD

**Issue by Zaixer** [tiberiuzuld/angular-gridster2#164]
It seems that the default mobileBreakpoint of 640 is applied initially even if another value have been set in options. So if for example the value is set to 200 and the container is initially 400 then it will stack the items but remove the stacking as soon as the container is adjusted.

**Comment by tiberiuzuld** [comment]
Hi @Zaixer ,

That seems to happen, looking into how to fix it.

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @Zaixer ,
Fixed in v4.0.3

Thanks,

**Comment by Zaixer** [comment]
thanks for fast fix :)

**Comment by Zaixer** [comment]
I tested some more and found that there is a case where the problem still appears: if the container to the grid is a fraction of the page width (for example a third of the page width).

If I set a breakpoint in setGridDimensions the problem dissapear so it might be some timing issue.

**Comment by tiberiuzuld** [comment]
Hi @Zaixer ,
Ok will investigate some more this week on how to fix it.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @Zaixer ,
I couldn't reproduce the issue anymore.
On the demo page there are a few moments that the size is 0 for gridster because of the mat-sidenav.

Without it from init the grid has size and renders as mobile from start.

Let me know if you find anyway to reproduce it each time.

Thanks

**Comment by Zaixer** [comment]
The problem is that it renders as mobile from start when it should render as desktop according to the breakpoint. Tried to set up an example in plunker but got stuck.

**Comment by tiberiuzuld** [comment]
Ok so the problem is that renders as mobile from start when it should be normal.

So is the reverse now.

Will have a look.

**Comment by tiberiuzuld** [comment]
Hi @Zaixer ,
I can't reproduce the issue.
On the demo the page is rendered in normal mode from start.

Thanks

**Comment by Zaixer** [comment]
It seems that the problem was that I had the grid nested inside an element with a [hidden] attribute that caused gridster to initiate the width to 0.

**Comment by tiberiuzuld** [comment]
Yes being hidden the width and height from JS api will be 0.

Thanks for letting me now.
