### ISSUE TITLE
Delete item not working on iPad

### ISSUE THREAD

**Issue by AlMuIssues** [tiberiuzuld/angular-gridster2#18]
Hello,

Link demo: https://tiberiuzuld.github.io/angular-gridster2/angular/
Run this demo in Chrome on PC works fine. 
If I run the demo in Chrome to simulate an iPad so I can't delete items with delete button. I expected click event, but I received stopEvent. I have the same behavior on real device ( iPad ). On iPhone works fine. I think that depends on different css for small devices.

**Comment by tiberiuzuld** [comment]
Hi @AlMuIssues 
Thank you for your bug report. Still need your help testing it, since I don't have an iPad.
It should be fixed now in v2.4.0, can you confirm this for me please?

**Comment by AlMuIssues** [comment]
Hi @tiberiuzuld 
delete of grid items in your demo and in my own application with angular-gridster2 v2.4.3 is still not working on iPad

**Comment by tiberiuzuld** [comment]
Hi @AlMuIssues ,
It may be an issue related to this https://github.com/angular/material2/issues/1316
Will try to see if I can get hold of the touchstart event instead of click

**Comment by tiberiuzuld** [comment]
Hi @AlMuIssues ,
This issue should be fixed for sure in v2.5.0 added the touchstart event on the remove button.
Btw this button is only in the demo application not in library itself.
Drag & Resize works with touch from the beginning.

**Comment by AlMuIssues** [comment]
It works fine.
Thanks.
