### ISSUE TITLE
Pushing right or left grid item to down when one grid item is resizing horizontally.

### ISSUE THREAD

**Issue by iamakashk** [tiberiuzuld/angular-gridster2#750]
Hi 

I am trying to implement following with angular gridster2
https://react-grid-layout.github.io/react-grid-layout/examples/3-messy.html.
![image](https://user-images.githubusercontent.com/19202603/123118206-0d4c8680-d460-11eb-8e57-bf8bf9392121.png)

When I resize element other grid items should move down if it expands to window size. I could not find any documentation for this. In my current implementation when I am resizing one grid item , it is increasing number of grid without pushing the other grid item down which is changing the default size and shape of the grid item. 

Can anyone help me on this?

Thanks in advance. !! :)

**Comment by gitalvininfo** [comment]
This should be an issue in your `gridType` option.  I guess your `gridType `is set to **"fit"**. 
Try changing it to `gridType: "fixed",` 

I can see in your link that it has been fixed already 😀

**Comment by iamakashk** [comment]
> This should be an issue in your `gridType` option. I guess your `gridType `is set to **"fit"**.
> Try changing it to `gridType: "fixed",`
> 
> I can see in your link that it has been fixed already 😀

Hi @gitalvininfo 
Thanks for your help. I tried doing the same but it did not resolve my problem. I have tried to setup same thing here 
https://stackblitz.com/edit/angular-gridster2-example?file=src%2Fapp%2Fgrid%2Fgrid.component.ts

Could you please have a look and help me out here ? Really stuck on this issue. 

Thanks in advance.

**Comment by gitalvininfo** [comment]
Hi @iamakashk 

Is this what you want to achieve? 

[stackblitz here](https://stackblitz.com/edit/angular-gridster2-example-ewewwz-szojrh?file=src%2Fapp%2Fgrid%2Fgrid.component.ts)

**Comment by gitalvininfo** [comment]
For your question 

> In my current implementation when I am resizing one grid item , it is increasing number of grid without pushing the other grid item down which is changing the default size and shape of the grid item.

Is this what you want to achieve?

[stackblitz link](https://stackblitz.com/edit/angular-gridster2-example-szojrh?file=src/app/grid/grid.component.ts)


Lastly for you first question

> When I resize element other grid items should move down if it expands to window size

I don't think this if this is possible yet in the package.
