### ISSUE TITLE
Error when installing packages

### ISSUE THREAD

**Issue by dedalusmax** [tiberiuzuld/angular-gridster2#8]
I can't install the packages after the last change:

D:\angular-gridster2>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.8
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: append-transform@^0.4.3
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.4.0, 0.3.0, 0.2.2, 0.2.1, 0.2.0
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'istanbul-lib-hook'
npm ERR! notarget

Can you please check this out?

**Comment by tiberiuzuld** [comment]
Hi @dedalusmax 
Just did a complete removal of node_modules, npm cache clean and npm install
Everything worked. Didn't get any errors.

Please try again with removing of node_modules and npm cache clean.

**Comment by tiberiuzuld** [comment]
Probably the error has to do with karma-coverage-istanbul-reporter updated the version from 0.3.0 to 1.0.0

**Comment by dedalusmax** [comment]
Hello @tiberiuzuld:
I did what you did, and npm install throw me:
`-- UNMET PEER DEPENDENCY zone.js@0.8.4

and npm start throws the following:

ERROR in D:/angular-gridster2/src/app/typings.d.ts (2,21): Cannot find name 'NodeModule'.)
webpack: Failed to compile.

node -v: v6.10.0
npm -v: 3.10.8

**Comment by tiberiuzuld** [comment]
The unmet peer dependency should not affect you.
Fixed the error in compilation.
Will not make another release since this is not affecting the deployed library only the demo app.

**Comment by dedalusmax** [comment]
ok, now the demo works fine.
but, when i try to install the library into my project with this:

rd node_modules /s
npm cache clean
npm install 
npm install angular-gridster2 

 i still get the error for unmet dependency:

D:\Auxcis2\Aucxis team project\Projects\Belgium\EPS\Zellik\Websites\EPS.ETrack>npm install angular-gridster2
angular2-webpack@1.0.0 D:\Auxcis2\Aucxis team project\Projects\Belgium\EPS\Zellik\Websites\EPS.ETrack
`-- angular-gridster2@2.0.2
  +-- UNMET PEER DEPENDENCY @angular/common@2.4.10
  `-- UNMET PEER DEPENDENCY zone.js@0.8.4

What I'm doing wrong?

**Comment by tiberiuzuld** [comment]
Made a new release v.2.0.3 with the dependencies stated more correctly.
But if you make an angular2 app then you shouldn't have any issues even if npm gives those warnings.

**Comment by dedalusmax** [comment]
this is my package.json:

{
  "name": "angular2-webpack",
  "version": "1.0.0",
  "description": "A webpack starter for Angular",
  "scripts": {
    "start": "webpack-dev-server --inline --progress --port 8080",
    "test": "karma start",
    "build": "rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail"
  },
  "license": "MIT",
  "dependencies": {
    "@angular/common": "2.4.0",
    "@angular/compiler": "2.4.0",
    "@angular/core": "2.4.0",
    "@angular/forms": "2.4.0",
    "@angular/http": "2.4.0",
    "@angular/platform-browser": "2.4.0",
    "@angular/platform-browser-dynamic": "2.4.0",
    "@angular/router": "3.4.0",
    "@webcomponents/custom-elements": "1.0.0-alpha.3",
    "clarity-angular": "0.8.4",
    "clarity-icons": "0.8.4",
    "clarity-ui": "0.8.4",
    "core-js": "2.4.1",
    "jquery": "3.1.1",
    "mutationobserver-shim": "0.3.2",
    "moment": "2.17.1",
    "ng2-translate": "5.0.0",
    "rxjs": "5.0.1",
    "zone.js": "0.7.4"
  },
  "devDependencies": {
    "@types/jasmine": "2.5.41",
    "@types/jquery": "^2.0.39",
    "@types/node": "^6.0.45",
    "angular2-template-loader": "^0.4.0",
    "awesome-typescript-loader": "^2.2.4",
    "css-loader": "^0.23.1",
    "copy-webpack-plugin": "^4.0.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "gulp": "~3.9.1",
    "gulp-util": "~3.0.8",
    "tslint": "^4.5.1",
    "gulp-tslint": "^7.1.0",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.15.0",
    "jasmine-core": "^2.4.1",
    "karma": "^1.2.0",
    "karma-jasmine": "^1.0.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.8.0",
    "node-sass": "~4.3.0",
    "null-loader": "^0.1.1",
    "phantomjs-prebuilt": "^2.1.7",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.2",
    "sass-loader": "~4.1.1",
    "style-loader": "^0.13.1",
    "typescript": "~2.0.10",
    "webpack": "^1.13.0",
    "webpack-dev-server": "^1.14.1",
    "webpack-merge": "^0.14.0"
  }
}

and this is my webpack's vendor.js:

import 'rxjs';

import 'clarity-icons/clarity-icons.min.css';
import 'mutationobserver-shim/dist/mutationobserver.min.js';
import '@webcomponents/custom-elements/custom-elements.min.js';
import 'clarity-icons';
import 'clarity-icons/shapes/essential-shapes.js';
import 'clarity-icons/shapes/social-shapes.js';
import 'clarity-icons/shapes/technology-shapes.js';
import 'clarity-ui/clarity-ui.min.css';

import 'ng2-translate';

import 'moment';
import 'moment/moment.js';

import 'angular-gridster2';

the application builds with webpack. BUT, when I start it, it throws me an error in chrome:

Error: Unexpected value 'GridsterModule' imported by the module 'DashboardModule' at SyntaxError.BaseError ...

I just can't include it in my app, and I don't know what is the reason for this. Is it possible that you try to build it with some test app that has the package.json as mine? And webpack with the vendor.js as this?
I would most appreciate it.

**Comment by tiberiuzuld** [comment]
I will have a look.

**Comment by tiberiuzuld** [comment]
Btw you don't have angular-gridster2 in your package.json

**Comment by dedalusmax** [comment]
yes, i know. i've installed it from the command prompt afterwards.

**Comment by dedalusmax** [comment]
the thing is: I'm truly overjoyed with your ng2 adaptation of gridster component, and we would like to use it, since it has everything what we need - according to demo. so, i would really wish to include it into our application but currently there are issues that prevent that. please try to test it with my config I've sent you and give me your feedback. 
thank you in advance!

**Comment by tiberiuzuld** [comment]
So made some new fixes for relative paths and stuff. Try out v2.0.6
For gridsterConfig : `import {GridsterConfig} from 'angular-gridster2/dist/gridsterConfig.interface';`
Worked for me. 
Will try to add it directly.
Tried till now to import in another angular-cli app and made the necessary fixes. 
If this is still not working for you will try the webpack starter.

**Comment by dedalusmax** [comment]
well, the problem is then apparently somewhere in the way webpack interprets this, since the error is the same:

Error: Unexpected value 'GridsterModule' imported by the module 'DashboardModule' at SyntaxError.BaseError [as constructor] (http://localhost:8080/vendor.js:1807:30) [<root>] at new SyntaxError (http://localhost:8080/vendor.js:2005:19) [<root>] at http://localhost:8080/vendor.js:18322:47 [<root>] at Array.forEach (native) [<root>] at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8080/vendor.js:18307:52) [<root>] at CompileMetadataResolver.getNgModuleSummary (http://localhost:8080/vendor.js:1....

**Comment by tiberiuzuld** [comment]
try to change  `import 'angular-gridster2';` to `import 'angular-gridster2/dist/gridster.module.js';`

**Comment by dedalusmax** [comment]
yes, i did. unfortunatelly, the same thing :(

**Comment by dedalusmax** [comment]
I think you are missing index.d.ts and metadata.json files, as I read through the forums. 

But best if you can test with the webpack, and with the versions from my package.json file to be sure.

**Comment by dedalusmax** [comment]
I just tried with another Angular 2 project, which uses systemjs configuration, and it also fails. 
Btw, there should be lodash installed within the package.json: 
"angular-gridster2": "^2.0.6",
    "lodash": "^4.17.4"

in my systemjs.config.js  I put: 
map: ...
'angular-gridster2': 'npm:angular-gridster2/dist/gridster.module.js',
      'lodash': 'npm:lodash/lodash.js'

After that, my app still won't work. I have the following error in Chrome:

http://localhost:3000/node_modules/angular-gridster2/dist/gridster.component 404 (Not Found)

together with some other errors pointing that the parts of the library are not found.

**Comment by tiberiuzuld** [comment]
So I tried the angular-cli app and worked.
Tried this webpack starter https://github.com/preboot/angular2-webpack 
This works but the `styles: [require('./style')]` doesn't work but from what I read is just a change a of configuration in `webpack.config.js` to make it work.

This error you get: ` Error: Unexpected value 'GridsterModule' imported by the module 'DashboardModule' at SyntaxError.BaseError `
is from what I read [here](https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.3620cza6h)
that is from using AOT which the library doesn't support yet. Need to do a lot of work to make it support.

For SystemJS I think you need to do 2 things:
1. `map: { 'angular-gridster2': 'node_modules/angular-gridster2'}`
2. `packages: {'angular2-library-example': {main: 'dist/gridster.module'}}`

I have no clue on what I need to change to make it compatible with all the module loaders that exist now. Or if is from the library side or the `module loader` side.

One solution was thinking just to publish the entire ts lib folder with an extra index.ts file with exports in it, and hope that everything will work.

**Comment by dedalusmax** [comment]
I think that the issue I experience with the webpack is the one explained in your mentioned article. So that is probably the way you should go.
I can try with the index.ts for the start.

**Comment by tiberiuzuld** [comment]
Hi @dedalusmax ,
Added the `lib/*` folder to the npm package.
Let me know if this helps you.

**Comment by tiberiuzuld** [comment]
Hi @dedalusmax ,
The library is now compatible with AOT, you should not have any more issues.

**Comment by Phota16** [comment]
when i ran npm install angular-gridster2 --save , It installed correctly without any error but i won't see the lib folder in my solution...When ran the dashboard sample project, it gives me same error like "Cannot find module './gridsterConfig.int
erface'.
webpack: Failed to compile.

**Comment by tiberiuzuld** [comment]
HI @Phota16 ,
`lib` folder is no longer part of the `npm install`.
In webpack config you should add `node_modules/angular-gridster2/dist/index.js`
If you use `angular-cli` will work automatically to import
